/* sql-formatter-disable */
\c product_catalogs

/* sql-formatter-enable */
CREATE TABLE IF NOT EXISTS products (
    product_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    supplier_id INTEGER,
    category_id INTEGER NOT NULL,
    unit_price NUMERIC NOT NULL DEFAULT 0,
    units_in_stock INTEGER NOT NULL DEFAULT 0,
    units_on_order INTEGER NOT NULL DEFAULT 1,
    discontinued BOOLEAN NOT NULL DEFAULT FALSE,
    discontinued_date TIMESTAMP WITH TIME ZONE
);

/* sql-formatter-enable */
CREATE TABLE IF NOT EXISTS categories (category_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL);

/* sql-formatter-disable */
GRANT SELECT,INSERT,DELETE,UPDATE ON categories TO operator;

/* sql-formatter-enable */
CREATE INDEX if NOT EXISTS ix_products_category_id ON products (category_id);

ALTER TABLE products
ADD FOREIGN key (category_id) REFERENCES categories (category_id) ON DELETE RESTRICT;

/* sql-formatter-disable */
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO operator;


CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    location TEXT NOT NULL
);

/* sql-formatter-disable */
GRANT SELECT,INSERT,DELETE,UPDATE ON suppliers TO operator;

/* sql-formatter-enable */
CREATE INDEX if NOT EXISTS ix_products_supplier_id ON products (supplier_id);

ALTER TABLE products
ADD FOREIGN key (supplier_id) REFERENCES suppliers (supplier_id) ON DELETE RESTRICT;

/* sql-formatter-disable */
GRANT SELECT,INSERT,DELETE,UPDATE ON products TO operator;
