version: "3"
services:
  dev:
    build:
      context: ./
      args:
        # For Linux, Change the permission by specifying UID / GID.
        "USER_UID": ${VSCODE_UID:-1000}
        "USER_GID": ${VSCODE_GID:-1000}
    environment:
      - DOTNET_ENVIRONMENT=Development
    tty: true
    volumes:
      - ..:/examples-dotnet-efcore
    working_dir: /examples-dotnet-efcore
