version: "3"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    volumes:
      - sqlserver-data:/var/opt/mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sql2022@Password
      - MSSQL_PID=Express
    networks:
      default:
        aliases:
          - sqlserver
volumes:
  sqlserver-data:
